-- AlterTable
ALTER TABLE "Ingredient"
ADD COLUMN "mlDensityGPerMl" DOUBLE PRECISION,
ADD COLUMN "gramsPerPiece" DOUBLE PRECISION,
ADD COLUMN "gramsPerHand" DOUBLE PRECISION,
ADD COLUMN "gramsPerTeaspoon" DOUBLE PRECISION,
ADD COLUMN "gramsPerTablespoon" DOUBLE PRECISION,
ADD COLUMN "gramsPerPinch" DOUBLE PRECISION,
ADD COLUMN "gramsPerCup" DOUBLE PRECISION,
ADD COLUMN "gramsPerSlice" DOUBLE PRECISION,
ADD COLUMN "gramsPerBunch" DOUBLE PRECISION,
ADD COLUMN "gramsPerCan" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Recipe"
ADD COLUMN "nutritionFat" DOUBLE PRECISION,
ADD COLUMN "nutritionCarbs" DOUBLE PRECISION,
ADD COLUMN "nutritionProtein" DOUBLE PRECISION,
ADD COLUMN "nutritionCalories" DOUBLE PRECISION,
ADD COLUMN "nutritionFiber" DOUBLE PRECISION,
ADD COLUMN "nutritionSugar" DOUBLE PRECISION,
ADD COLUMN "nutritionSalt" DOUBLE PRECISION,
ADD COLUMN "nutritionTotalGrams" DOUBLE PRECISION,
ADD COLUMN "nutritionWarningCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "nutritionHasEstimatedConversions" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "nutritionComputedAt" TIMESTAMP(3);
